language: python
python:
  - "3.7"
# command to install dependencies
before_install:
  - gem install rake
install:
  - pip3 install requests pyyaml pytest pytest-cov
  - pip3 install matplotlib
# command to run tests
script:
  - cd travelplanner
  - pytest 
  - pytest --cov=./
  - python3 -m doctest -v Journey.py
